<?php
/**
 * Created by PhpStorm.
 * User: heliobentes
 * Date: 6/20/17
 * Time: 7:24 PM
 */


use Bents\Core\Globalization\Globalization;
use Bents\Core\View;

View::$layout = "Shared/_Layout";
View::$title = "Home Page"


?>

<?php View::$cssBundle[] = <<<EOT
<style type="text/css" media="screen">
    .body {}
</style>
<style type="text/css">
     .body2 {}
</style>
EOT;
View::$cssBundle[] = <<<EOT
<style type="text/css">
     .body3 {}
</style>
EOT;
View::$cssBundle[] = <<<EOT
<style> .body4 {}</style>
EOT;
View::$cssBundle[] = <<<EOT
EOT;
?>
<button onclick="$('.content').removeClass('one').removeClass('three').addClass('two')" class="btn btn-primary">Open container 2</button>

<button onclick="AddPop('success','fa fa-check','Success Notification!','Success notification text goes here. It can be big or small. It depends just on the notification.',['#','Link'])" class="btn btn-success margin-10">Add success pop</button>
<button onclick="AddPop('info','fa fa-info-circle','Info Notification!','Info notification text goes here. It can be big or small. ',['#','Link'])" class="btn btn-info margin-10">Add info pop</button>
<button onclick="AddPop('danger','fa fa-exclamation-triangle','Danger Notification!','Danger notification text goes here. It depends just on the notification.',['#','Link'])" class="btn btn-danger margin-10">Add danger pop</button>
<button onclick="AddPop('warning','fa fa-exclamation-circle','Warning Notification!','Warning notification text goes here. It can be big or small. It depends just on the notification.',['#','Link'])" class="btn btn-warning margin-10">Add warning pop</button>

<?php echo View::$bag['teste']; ?>
<br>
<?php echo $this->__('Write test like Magento'); ?>
<br>
<?php echo $this->__('how_are_you'); ?>
<br>
<?php echo $this->__('what_is_your_name'); ?>
<br>
<?php echo $this->__('how_old_are_you'); ?>
<br>
We are using <?php echo Globalization::GetLanguage(); ?> as the language.
<br>
<br>
We are using <?php echo Globalization::GetLanguage(); ?> as the language.
<br>
<br>
We are using <?php echo Globalization::GetLanguage(); ?> as the language.
<br>
<br>
We are using <?php echo Globalization::GetLanguage(); ?> as the language.
<br>
<br>
We are using <?php echo Globalization::GetLanguage(); ?> as the language.
<br>
<br>
We are using <?php echo Globalization::GetLanguage(); ?> as the language.
<br>
<br>
We are using <?php echo Globalization::GetLanguage(); ?> as the language.
<br>
<br>
We are using <?php echo Globalization::GetLanguage(); ?> as the language.
<br>
<br>
We are using <?php echo Globalization::GetLanguage(); ?> as the language.
<br>
<?php echo View::$bag['teste']; ?>
<br>
<?php echo $this->__('Write test like Magento'); ?>
<br>
<?php echo $this->__('how_are_you'); ?>
<br>
<?php echo $this->__('what_is_your_name'); ?>
<br>
<?php echo $this->__('how_old_are_you'); ?>
<?php echo View::$bag['teste']; ?>
<br>
<?php echo $this->__('Write test like Magento'); ?>
<br>
<?php echo $this->__('how_are_you'); ?>
<br>
<?php echo $this->__('what_is_your_name'); ?>
<br>
<?php echo $this->__('how_old_are_you'); ?>
<?php echo View::$bag['teste']; ?>
<br>
<?php echo $this->__('Write test like Magento'); ?>
<br>
<?php echo $this->__('how_are_you'); ?>
<br>
<?php echo $this->__('what_is_your_name'); ?>
<br>
<?php echo $this->__('how_old_are_you'); ?>
<?php echo View::$bag['teste']; ?>
<br>
<?php echo $this->__('Write test like Magento'); ?>
<br>
<?php echo $this->__('how_are_you'); ?>
<br>
<?php echo $this->__('what_is_your_name'); ?>
<br>
<?php echo $this->__('how_old_are_you'); ?>
<?php echo View::$bag['teste']; ?>
<br>
<?php echo $this->__('Write test like Magento'); ?>
<br>
<?php echo $this->__('how_are_you'); ?>
<br>
<?php echo $this->__('what_is_your_name'); ?>
<br>
<?php echo $this->__('how_old_are_you'); ?>
<?php View::$jsBundle[] = <<<EOT
<script type="application/javascript" async defer>
//comment 2
    let b = 1;                       
    //comment 1
</script>
<script type="application/javascript" async>
    let c = 2;
</script>
EOT;
View::$jsBundle[] = <<<EOT
<script type="application/javascript">
    let d = 3;
</script>
EOT;
View::$jsBundle[] = <<<EOT
<script>let e = 4; //comment</script>
EOT;
View::$jsBundle[] = <<<EOT
EOT;
?>
