<?php
/**
 * Created by PhpStorm.
 * User: heliobentes
 * Date: 6/20/17
 * Time: 7:24 PM
 */


use Bents\Core\Globalization\Globalization;
use Bents\Core\View;

View::$layout = "Shared/_Layout";
View::$title = "Home Page"


?>

<?php View::$cssBundle[] = <<<EOT
<style type="text/css" media="screen">
    .body {}
</style>
<style type="text/css">
     .body2 {}
</style>
EOT;
View::$cssBundle[] = <<<EOT
<style type="text/css">
     .body3 {}
</style>
EOT;
View::$cssBundle[] = <<<EOT
<style> .body4 {}</style>
EOT;
View::$cssBundle[] = <<<EOT
EOT;
?>

<ul>
    <li>1</li>
    <li>2</li>
    <li>3</li>
    <li>4</li>
    <li>5 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
</ul>

<?php echo View::$bag['teste']; ?>
<br>
<?php echo Globalization::Resource('how_are_you'); ?>
<br>
<?php echo Globalization::Resource('what_is_your_name'); ?>
<br>
<?php echo Globalization::Resource('how_old_are_you'); ?>
<br>
We are using <?php echo Globalization::GetLanguage(); ?> as the language.
<br>
<?php View::$jsBundle[] = <<<EOT
<script type="application/javascript" async defer>
//comment 2
    let b = 1;                       
    //comment 1
</script>
<script type="application/javascript" async>
    let c = 2;
</script>
EOT;
View::$jsBundle[] = <<<EOT
<script type="application/javascript">
    let d = 3;
</script>
EOT;
View::$jsBundle[] = <<<EOT
<script>let e = 4; //comment</script>
EOT;
View::$jsBundle[] = <<<EOT
EOT;
?>
