<?php

use Bents\Core\View;

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?php echo View::$title; ?> | Default Application</title>
    <link rel="apple-touch-icon" sizes="57x57" href="/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
    <link rel="manifest" href="/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/favicon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <?php View::RenderCSSBundle(); ?>
</head>
<body>
<nav class="navbar">
    <div class="logo">
        <a href="/"><img src="/images/logo.png" height="40" width="136"></a>
    </div>
    <i class="fa fa-bars" id="menu-icon"></i>
    <ul class="nav" id="main-nav">
        <li class="active"><a href="#"><i class="far fa-newspaper"></i> Mural</a>
            <ul class="subnav open">
                <li class="active"><a href="#"><i class="far fa-newspaper"></i> Mural</a></li>
                <li ><a href="#"><i class="fa fa-calendar-plus"></i> New appointment</a></li>
                <li><a href="#"><i class="fa fa-user-plus"></i> New customer</a></li>
                <li><a href="#"><i class="fa fa-plus"></i> New property</a></li>
                <li class="nav-extra"><a class="btn btn-primary" data-jq-dropdown="#dropdown-edit-mural"><i class="fa fa-edit"></i> Edit</a></li>
            </ul>
        </li>
        <li><a href="#"><i class="fa fa-home"></i> Properties</a>
            <ul class="subnav">
                <li><a href="#"><i class="fa fa-plus"></i> New property</a></li>
                <li><a href="#"><i class="fa fa-home"></i> Properties</a></li>
            </ul>
        </li>
        <li><a href="#"><i class="fa fa-suitcase"></i> CRM</a>
            <ul class="subnav">
                <li><a href="#"><i class="fab fa-pagelines"></i> Leads</a></li>
                <li><a href="#"><i class="fa fa-user-plus"></i> New customer</a></li>
                <li class="active"><a href="#"><i class="fa fa-users"></i> Customers</a></li>
                <li><a href="#"><i class="fa fa-calendar-plus"></i> New appointment</a></li>
                <li><a href="#"><i class="far fa-calendar-alt"></i> Appointments</a></li>
                <li><a href="#"><i class="fa fa-plus"></i> New dealing</a></li>
                <li><a href="#"><i class="far fa-handshake"></i> Dealings</a></li>
            </ul>
        </li>
        <li><a href="#"><i class="fa fa-desktop"></i> WebSite</a>
            <ul class="subnav">
                <li><a href="#"><i class="fa fa-paint-brush"></i> Layout & design</a></li>
                <li class="active"><a href="#"><i class="fa fa-paper-plane"></i> Logo</a></li>
                <li><a href="#"><i class="fa fa-columns"></i> Extra pages</a></li>
                <li><a href="#"><i class="fab fa-google"></i> SEO & meta tags</a></li>
                <li><a href="#"><i class="fa fa-link"></i> My domain name (URL)</a></li>
                <li><a href="#"><i class="fa fa-phone-square"></i> Contact information</a></li>
            </ul>
        </li>
    </ul>
    <ul class="nav-right">
        <li><a href="#" title="Settings"><i class="fa fa-cogs"></i></a></li>
        <li><a href="#" title="Help"><i class="fa fa-question-circle"></i></a></li>
        <li class="notifications" id="notifications-icon"><a href="#"><i class="fa fa-bell"></i><i class="far fa-bell"></i></a></li>
        <li ><div class="user-icon" data-jq-dropdown="#dropdown-user">HB</div></li>
    </ul>
</nav>
<div class="content three">
    <div class="container" id="main-container">
        <h1 class="title">Title for column 1 very big overflow of text</h1>
        <div class="content">
        <?php View::RenderBody(); ?>
        </div>
    </div>
    <div class="container" id="second-container">
        <h1 class="title">Title for column 2 very big overflow of text<small>Subtitle for column 2</small></h1>
        <i class="far fa-times-circle close-container" id="close-container-2"></i>
        <div class="content">
            Content for column 2
            <button onclick="$('.content').removeClass('two').removeClass('one').addClass('three')" class="btn btn-primary">Open container 3</button>
        </div>
    </div>

    <div class="container" id="third-container">
        <h1 class="title">Title for column 3 very big overflow of text</h1>
        <i class="far fa-times-circle  close-container" id="close-container-3"></i>
        <div class="content">
            Content for column 3
        </div>
    </div>
</div>
<!-- BEGIN Dropdown User - TopMenu-->
<div id="dropdown-user" class="jq-dropdown jq-dropdown-tip jq-dropdown-anchor-right">
    <ul class="jq-dropdown-menu">
        <li><a href="#1"><i class="fa fa-user-circle"></i> My profile</a></li>
        <li class="jq-dropdown-divider"></li>
        <li><a href="#1"><i class="fa fa-address-card"></i> My account</a></li>
        <li><a href="#2"><i class="fa fa-user-secret"></i>Users & permissions</a></li>
        <li class="jq-dropdown-divider"></li>
        <li><a href="#5"><i class="fa fa-sign-out-alt"></i>Logout</a></li>
    </ul>
</div>
<!-- END Dropdown User - TopMenu-->

<!-- BEGIN Dropdown Edit Mural - TopMenu-->
<div id="dropdown-edit-mural" class="jq-dropdown jq-dropdown-tip jq-dropdown-anchor-right">
    <ul class="jq-dropdown-menu">
        <li ><label><input type="checkbox"><i class="fa fa-calendar-plus"></i> New appointment</label></li>
        <li><label><input type="checkbox"><i class="fa fa-user-plus"></i> New customer</label></li>
        <li><label><input type="checkbox"><i class="fa fa-plus"></i> New property</label></li>
        <li><label><input type="checkbox"><i class="fa fa-plus"></i> New dealing</label></li>
        <li><label><input type="checkbox"><i class="fa fa-home"></i> Properties</label></li>
    </ul>
</div>
<!-- END Dropdown Edit Mural - TopMenu-->

<!-- BEGIN Notifications -->
<div id="notifications" class="">
    <div id="notification-backdrop"></div>
    <h3><?php echo View::__('Notifications'); ?> <button class="btn btn-link" id="btn-clear-notifications"><?php echo View::__('Clear all'); ?></button> </h3>
    <div class="notifications-container">
    <ul id="notifications-list">
        <li class="success">
            <div class="notification-icon">
                <i class="fa fa-check"></i>
            </div>
            <div class="notification-content">
                <h5 class="notification-title">Success notification!</h5>
                <p>Success notification text goes here. It can be big or small. It depends just on the notification.</p>
                <a href="#"><i class="fa fa-eye"></i> Link with icon</a><a href="#">Another link</a>
            </div>
            <i class="fa fa-times notification-close"></i>
        </li>
        <li class="info">
            <div class="notification-icon">
                <i class="fa fa-info-circle"></i>
            </div>
            <div class="notification-content">
                <h5 class="notification-title">Success notification!</h5>
                <p>Success notification text goes here. It can be big or small. It depends just on the notification.</p>
                <a href="#"><i class="fa fa-eye"></i> Link with icon</a><a href="#">Another link</a>
            </div>
            <i class="fa fa-times notification-close"></i>
        </li>
        <li class="danger">
            <div class="notification-icon">
                <i class="fa fa-exclamation-triangle"></i>
            </div>
            <div class="notification-content">
                <h5 class="notification-title">Success notification!</h5>
                <p>Success notification text goes here. It can be big or small. It depends just on the notification.</p>
                <a href="#"><i class="fa fa-eye"></i> Link with icon</a><a href="#">Another link</a>
            </div>
            <i class="fa fa-times notification-close"></i>
        </li>
        <li class="warning">
            <div class="notification-icon">
                <i class="fa fa-exclamation-circle"></i>
            </div>
            <div class="notification-content">
                <h5 class="notification-title">Success notification!</h5>
                <p>Success notification text goes here. It can be big or small. It depends just on the notification.</p>
                <a href="#"><i class="fa fa-eye"></i> Link with icon</a><a href="#">Another link</a>
            </div>
            <i class="fa fa-times notification-close"></i>
        </li>
        <li class="success">
            <div class="notification-icon">
                <i class="fa fa-check"></i>
            </div>
            <div class="notification-content">
                <h5 class="notification-title">Success notification!</h5>
                <p>Success notification text goes here. It can be big or small. It depends just on the notification.</p>
                <a href="#"><i class="fa fa-eye"></i> Link with icon</a><a href="#">Another link</a>
            </div>
            <i class="fa fa-times notification-close"></i>
        </li>
        <li class="info">
            <div class="notification-icon">
                <i class="fa fa-info-circle"></i>
            </div>
            <div class="notification-content">
                <h5 class="notification-title">Success notification!</h5>
                <p>Success notification text goes here. It can be big or small. It depends just on the notification.</p>
                <a href="#"><i class="fa fa-eye"></i> Link with icon</a><a href="#">Another link</a>
            </div>
            <i class="fa fa-times notification-close"></i>
        </li>
        <li class="danger">
            <div class="notification-icon">
                <i class="fa fa-exclamation-triangle"></i>
            </div>
            <div class="notification-content">
                <h5 class="notification-title">Success notification!</h5>
                <p>Success notification text goes here. It can be big or small. It depends just on the notification.</p>
                <a href="#"><i class="fa fa-eye"></i> Link with icon</a><a href="#">Another link</a>
            </div>
            <i class="fa fa-times notification-close"></i>
        </li>
        <li class="warning">
            <div class="notification-icon">
                <i class="fa fa-exclamation-circle"></i>
            </div>
            <div class="notification-content">
                <h5 class="notification-title">Success notification!</h5>
                <p>Success notification text goes here. It can be big or small. It depends just on the notification.</p>
                <a href="#"><i class="fa fa-eye"></i> Link with icon</a><a href="#">Another link</a>
            </div>
            <i class="fa fa-times notification-close"></i>
        </li>
        <li class="success">
            <div class="notification-icon">
                <i class="fa fa-check"></i>
            </div>
            <div class="notification-content">
                <h5 class="notification-title">Success notification!</h5>
                <p>Success notification text goes here. It can be big or small. It depends just on the notification.</p>
                <a href="#"><i class="fa fa-eye"></i> Link with icon</a><a href="#">Another link</a>
            </div>
            <i class="fa fa-times notification-close"></i>
        </li>
        <li class="info">
            <div class="notification-icon">
                <i class="fa fa-info-circle"></i>
            </div>
            <div class="notification-content">
                <h5 class="notification-title">Success notification!</h5>
                <p>Success notification text goes here. It can be big or small. It depends just on the notification.</p>
                <a href="#"><i class="fa fa-eye"></i> Link with icon</a><a href="#">Another link</a>
            </div>
            <i class="fa fa-times notification-close"></i>
        </li>
        <li class="danger">
            <div class="notification-icon">
                <i class="fa fa-exclamation-triangle"></i>
            </div>
            <div class="notification-content">
                <h5 class="notification-title">Success notification!</h5>
                <p>Success notification text goes here. It can be big or small. It depends just on the notification.</p>
                <a href="#"><i class="fa fa-eye"></i> Link with icon</a><a href="#">Another link</a>
            </div>
            <i class="fa fa-times notification-close"></i>
        </li>
        <li class="warning">
            <div class="notification-icon">
                <i class="fa fa-exclamation-circle"></i>
            </div>
            <div class="notification-content">
                <h5 class="notification-title">Success notification!</h5>
                <p>Success notification text goes here. It can be big or small. It depends just on the notification.</p>
                <a href="#"><i class="fa fa-eye"></i> Link with icon</a><a href="#">Another link</a>
            </div>
            <i class="fa fa-times notification-close"></i>
        </li>
    </ul>
    </div>
</div>
<!-- END Notifications -->
<?php View::RenderJavaScriptBundle(); ?>
</body>
</html>