<?php

use Bents\Core\View;

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?php echo View::$title; ?> | Default Application</title>
    <link rel="apple-touch-icon" sizes="57x57" href="/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
    <link rel="manifest" href="/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/favicon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <?php View::RenderCSSBundle(); ?>
</head>
<body class="menu-open">
<nav class="navbar">
    <div class="logo">
        <a href="/"><img src="/images/logo.png" height="40" width="136"></a>
    </div>
    <i class="fa fa-bars" id="menu-icon"></i>
    <ul class="nav" id="main-nav">
        <li class="active"><a href="#"><i class="fa fa-newspaper-o"></i> Mural</a>
            <ul class="subnav open">
                <li><a href="#"><i class="fa fa-user-plus"></i> New User</a></li>
                <li class="active"><a href="#"><i class="fa fa-calendar-plus-o"></i> New Appointment</a></li>
                <li><a href="#"><i class="fa fa-plus"></i> New Property</a></li>
                <li class="nav-extra"><a class="btn btn-primary"><i class="fa fa-pencil"></i> Edit</a></li>
            </ul>
        </li>
        <li><a href="#"><i class="fa fa-home"></i> Properties</a>
            <ul class="subnav">
                <li><a href="#"><i class="fa fa-plus"></i> New property</a></li>
                <li><a href="#"><i class="fa fa-home"></i> List properties</a></li>
            </ul>
        </li>
        <li><a href="#"><i class="fa fa-suitcase"></i> CRM</a></li>
        <li><a href="#"><i class="fa fa-desktop"></i> WebSite</a></li>
    </ul>
    <ul class="nav-right">
        <li><a href="#"><i class="fa fa-cogs"></i></a></li>
        <li><a href="#"><i class="fa fa-question-circle"></i></a></li>
        <li class="notifications none"><a href="#"><i class="fa fa-bell-o"></i></a></li>
        <li ><div class="user-icon" data-jq-dropdown="#dropdown-user">HB</div></li>
    </ul>
</nav>
<div class="content two">
    <div class="container" id="main-container">
        <?php View::RenderBody(); ?>
    </div>
    <div class="container" id="second-container">
    </div>

    <div class="container" id="third-container">
    </div>
</div>
<!-- BEGIN Dropdown User - TopMenu-->
<div id="dropdown-user" class="jq-dropdown jq-dropdown-tip jq-dropdown-anchor-right">
    <ul class="jq-dropdown-menu">
        <li><a href="#1"><i class="fa fa-address-card"></i> My Account</a></li>
        <li><a href="#2"><i class="fa fa-user-secret"></i>Users & Permissions</a></li>
        <li class="jq-dropdown-divider"></li>
        <li><a href="#5"><i class="fa fa-sign-out"></i>Logout</a></li>
    </ul>
</div>
<!-- END Dropdown User - TopMenu-->
<?php View::RenderJavaScriptBundle(); ?>
</body>
</html>