<?php
/**
 * Created by PhpStorm.
 * User: heliobentes
 * Date: 1/2/18
 * Time: 1:34 PM
 */

use Bents\Core\Globalization\Globalization;
use Bents\Core\View;

View::$layout = 'Shared/_Layout';
View::$title = View::__("Add a new property");


?>
<div class="tabs">
    <ul class="tabs-navigation">
        <li class="active"><i class="fa fa-map-marker-alt"></i></li>
        <li><i class="fa fa-ticket-alt"></i></li>
        <li><i class="fa fa-tasks"></i></li>
        <li><i class="fa fa-dollar-sign"></i></li>
        <li><i class="fa fa-file-alt"></i></li>
        <li><i class="far fa-images"></i></li>
        <li class="actions"> <button class="btn btn-success"><i class="fa fa-save"></i> Save this property</button></li>
    </ul>
    <ul class="tabs-contents">
        <li class="active open" >

            <div class="row">

                <div class="side-col">
                    <h2><i class="fa fa-map-marker-alt"></i> Property address</h2>
                    <p>Start by adding the address to this property.</p>
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d83327.3577582379!2d-123.19394341241967!3d49.25782631999733!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x548673f143a94fb3%3A0xbb9196ea9b81f38b!2zVmFuY8O0dmVyLCBCQw!5e0!3m2!1spt-BR!2sca!4v1515026670031" width="100%" height="200" frameborder="0" style="border:0" allowfullscreen></iframe>
                    <hr class="divisor"/>
                </div>
                <div class="main-col">
                    <div class="field">
                        Postal Code
                        <input type="text" size="5">
                        <small>Type the postal code and the system will fill the other fields</small>
                    </div>
                    <div class="field inline">

                        Country
                        <select class="select2">
                            <option value="BR">Brazil</option>
                            <option value="CA">Canada</option>
                            <option value="US">United States</option>
                        </select>

                    </div>
                    <div class="field inline">

                        Province
                        <select class="select2">
                            <option value="AB">Alberta</option>
                            <option value="BC">British Columbia</option>
                            <option value="MB">Manitoba</option>
                            <option value="NB">New Brunswick</option>
                            <option value="NL">Newfoundland and Labrador</option>
                            <option value="NS">Nova Scotia</option>
                            <option value="ON">Ontario</option>
                            <option value="PE">Prince Edward Island</option>
                            <option value="QC">Quebec</option>
                            <option value="SK">Saskatchewan</option>
                            <option value="NT">Northwest Territories</option>
                            <option value="NU">Nunavut</option>
                            <option value="YT">Yukon</option>
                        </select>

                    </div>
                    <div class="field inline">

                        City
                        <select class="select2">
                            <option value="AB">Alberta</option>
                            <option value="BC">British Columbia</option>
                            <option value="MB">Manitoba</option>
                            <option value="NB">New Brunswick</option>
                            <option value="NL">Newfoundland and Labrador</option>
                            <option value="NS">Nova Scotia</option>
                            <option value="ON">Ontario</option>
                            <option value="PE">Prince Edward Island</option>
                            <option value="QC">Quebec</option>
                            <option value="SK">Saskatchewan</option>
                            <option value="NT">Northwest Territories</option>
                            <option value="NU">Nunavut</option>
                            <option value="YT">Yukon</option>
                        </select>

                    </div>
                    <div class="clear"></div>
                    <div class="field inline">
                        Unit #
                        <input type="text" size="3">

                    </div>
                    <div class="field inline">

                        Address
                        <input type="text" size="50">

                    </div>


                </div>

            </div>
        </li>
        <li >


            <div class="row">

                <div class="side-col">
                    <h2><i class="fa fa-ticket-alt"></i> Basic information</h2>
                    <p>Start by adding the address to this property.</p>
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d83327.3577582379!2d-123.19394341241967!3d49.25782631999733!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x548673f143a94fb3%3A0xbb9196ea9b81f38b!2zVmFuY8O0dmVyLCBCQw!5e0!3m2!1spt-BR!2sca!4v1515026670031" width="100%" height="200" frameborder="0" style="border:0" allowfullscreen></iframe>
                    <hr class="divisor"/>
                </div>
                <div class="main-col">

                    <div class="field">
                        Field label
                        <input type="text">

                    </div>
                    <div class="field inline">

                        Field label
                        <input type="text">

                    </div>
                    <div class="field inline">

                        Field label
                        <input type="text">

                    </div>
                    <div class="field">
                        Field label
                        <div class="input-group">
                            <span>$</span>
                            <input type="text">
                            <button class="btn btn-success"><i class="fa fa-eye"></i> Go</button>
                        </div>
                    </div>


                    <div class="field">

                        Field label
                        <div class="input-group">
                            <span>$</span>
                            <input type="text">
                        </div>

                    </div>

                    <div class="field">
                        Field label
                        <div class="input-group">
                            <input type="text">
                            <span>$</span>
                        </div>
                    </div>
                    <div class="field">
                        Field label
                        <div class="input-group">
                            <button class="btn btn-danger"><i class="fa fa-eye"></i> Go</button>
                            <input type="text">
                        </div>

                    </div>

                    <div class="field">

                        Field label
                        <div class="input-group">
                            <button class="btn btn-success"><i class="fa fa-eye"></i> Go</button>
                            <input type="text">
                            <span>$</span>
                        </div>
                    </div>

                    <div class="field">
                        Field label
                        <div class="input-group">
                            <input type="text">
                            <button class="btn btn-danger"><i class="fa fa-eye"></i> Go</button>
                        </div>
                    </div>
                    <div class="field">
                        Select
                        <select class="select2">
                            <option>Select option 1</option>
                            <option>Select option 2 a bit bigger</option>
                            <option>Select option 3 too much bigger than the other options</option>
                            <option>Select option 4</option>
                            <option>Small</option>
                            <option>Select option 5</option>
                        </select>
                    </div>

                    <div class="field">
                        Select
                        <select class="select2" multiple>
                            <option>Select option 1</option>
                            <option>Select option 2 a bit bigger</option>
                            <option>Select option 3 too much bigger than the other options</option>
                            <option>Select option 4</option>
                            <option>Small</option>
                            <option>Select option 5</option>
                        </select>
                    </div>

                    <div class="field">
                        Field label
                        <div class="input-group" data-trigger="spinner">
                            <button class="btn btn-default" data-spin="down"><i class="fa fa-minus"></i></button>
                            <input type="text">
                            <button class="btn btn-default" data-spin="up"><i class="fa fa-plus"></i></button>
                        </div>
                    </div>


                    <div class="field">
                        Field label
                        <textarea>Teste</textarea>
                    </div>

                </div>

            </div>
        </li>
        <li>
            <div class="row">

                <div class="side-col">
                    <h2><i class="fa fa-tasks"></i> Features</h2>
                    <p>Start by adding the address to this property.</p>
                    <hr class="divisor"/>
                </div>
                <div class="main-col">
                </div>
            </div>
        </li>
        <li>
            <div class="row">

                <div class="side-col">
                    <h2><i class="fa fa-dollar-sign"></i> Values & prices</h2>
                    <p>Start by adding the address to this property.</p>
                    <hr class="divisor"/>
                </div>
                <div class="main-col">
                </div>
            </div>
        </li>
        <li>
            <div class="row">

                <div class="side-col">
                    <h2><i class="fa fa-file-alt"></i> Title & description</h2>
                    <p>Start by adding the address to this property.</p>
                    <hr class="divisor"/>
                </div>
                <div class="main-col">
                </div>
            </div>
        </li>
        <li>
            <div class="row">

                <div class="side-col">
                    <h2><i class="fa fa-images"></i> Images</h2>
                    <p>Start by adding the address to this property.</p>
                    <hr class="divisor"/>
                </div>
                <div class="main-col">
                </div>
            </div>
        </li>
    </ul>
    <div class="actions-bottom"><button class="btn btn-success"><i class="fa fa-save"></i> Save this property</button></div>
</div>

