<?php
/**
 * Created by PhpStorm.
 * User: heliobentes
 * Date: 6/20/17
 * Time: 7:24 PM
 */

use Bents\Core\View;
use Bents\Core\Utils\Numbers;
View::$layout = "Shared/_Layout";
View::$title = View::__("Property details");
//echo '<pre>';
//print_r(View::$model);
/**
 * @var $property \Bents\App\Model\Property
 */
$property = View::$model;
?>
<!--</pre>-->

<div class="row" id="property">
    <div class="main-col">
        <h4><?php echo View::__('MLS® #:'). ' '.$property->mlsNumber;?></h4>
        <div class="tag-availability">
            <strong>Availability: </strong><?php echo \Bents\Core\Utils\DateTime::Format($property->availability); ?>
        </div>
        <h2>Property title goes here</h2>
        <ul class="blocks">
           <li>
               <i class="fa fa-building"></i>
               <?php echo $property->Type->type; ?>
           </li>
            <li>
                <i class="fa fa-bed"></i>
                <?php echo $property->bedrooms; ?>
                bedroom<?php if($property->bedrooms>1){ echo "s";}?>
            </li>

            <li>
                <i class="fa fa-bath"></i>
                <?php echo $property->bathrooms; ?>
                bathroom<?php if($property->bathrooms>1){ echo "s";}?>
            </li>
            <li>
                <i class="fa fa-arrows-alt-h"></i>
                <?php echo $property->area.' '. $property->areaUnit;?>
            </li>

            <li>
                <i class="fa fa-car"></i>
                <?php echo $property->Parking->parking; ?>
            </li>
            <li>
                <i class="fa fa-utensils"></i>
                <?php echo $property->Laundry->laundry; ?>
            </li>
        </ul>
        <ul class="pictures">
            <?php $i = 0;
            foreach ($property->Images as $image) {

                ?>
                <li <?php if ($i > 4) {
                    echo 'class="hidden"';
                } ?> style="background-image: url(/images/property/<?php echo $image->url; ?>)">
                    <?php if($image->label!=''){ echo "<span> $image->label</span>"; } ?></li>
                <?php

                $i++;
            }

            if (count($property->Images) >5) {
                echo '<li class="expander"><button class="btn btn-default" onclick="$(\'.pictures li.hidden\').slideToggle(\'fast\'); if($(this).find(\'span\').html()==\'Hide some\'){ $(this).find(\'span\').html(\'Show more\'); } else{ $(this).find(\'span\').html(\'Hide some\'); }"><i class="fa fa-images"></i> <span>Show more</span> images</button> </li>';
            }
            ?>

        </ul>
        <ul class="values">
            <li>
                <?php echo $property->currency.' '.Numbers::Format($property->sellingPrice,0); ?>
                <small>Selling price</small>
            </li>
            <li>

                <?php echo $property->currency.' '.Numbers::Format($property->rentalPrice,0); ?>
                <small>Rental price</small>
            </li>
            <li>
                <?php echo $property->currency.' '.Numbers::Format($property->condoExpenses); ?>
                <small>Condo expenses</small>
            </li>
        </ul>
        <hr class="divisor">
        <pre>
<?php echo $property->description; ?>
        </pre>
        <hr class="divisor"/>
    </div>
    <div class="side-col">
        <h2><i class="fa fa-map-marker-alt"></i>
            <?php echo View::__('Property address'); ?></h2>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d83327.3577582379!2d-123.19394341241967!3d49.25782631999733!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x548673f143a94fb3%3A0xbb9196ea9b81f38b!2zVmFuY8O0dmVyLCBCQw!5e0!3m2!1spt-BR!2sca!4v1515026670031"
                width="100%" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
        <address>
        <?php $Address = $property->Address;

        echo '<span>#'.preg_replace('~#~','',$Address->unitNumber) .' '.$Address->streetNumber .' '.$Address->address.'</span>'
            .$Address->region.' - '.$Address->area.'<br/>'
            .$Address->city.' - '.$Address->province.' - '.$Address->country.'<br/>'
            .$Address->postalCode;
        ?>
        </address>
        <hr class="divisor"/>

        <h2><i class="fa fa-tasks"></i> <?php echo View::__('Features'); ?></h2>
        <ul class="features">
            <?php foreach ($property->Features as $feature){
                ?>
            <li>
            <i class="fa fa-check"></i>
            <?php echo $feature->feature; ?>
            </li>
            <?php
            }
            ?>
        </ul>
    </div>
</div>

